"use client";

import React, { useState } from "react";
import { Header } from "@/components/Header";
import { FileUpload } from "@/components/FileUpload";
import { SystemOverview } from "@/components/SystemOverview";
import { DiagnosticsDashboard } from "@/components/DiagnosticsDashboard";
import { CollectorReport, DiagnoseResponse } from "@/lib/types";
import { runDiagnosis } from "@/lib/api";

export default function Home() {
  const [report, setReport] = useState<CollectorReport | null>(null);
  const [fileName, setFileName] = useState<string>("");
  const [diagnosis, setDiagnosis] = useState<DiagnoseResponse | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [isAiRewrite, setIsAiRewrite] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const handleReportLoaded = async (uploadedReport: CollectorReport, name: string) => {
    setReport(uploadedReport);
    setFileName(name);
    setError(null);
    setIsLoading(true);

    try {
      const result = await runDiagnosis(uploadedReport, isAiRewrite);
      setDiagnosis(result);
    } catch (err: unknown) {
      console.error(err);
      setError(
        err instanceof Error
          ? err.message
          : "Failed to connect to diagnostic backend API at http://localhost:8000."
      );
    } finally {
      setIsLoading(false);
    }
  };

  const handleToggleAiRewrite = async () => {
    if (!report) return;
    const newAiState = !isAiRewrite;
    setIsAiRewrite(newAiState);
    setIsLoading(true);
    setError(null);

    try {
      const result = await runDiagnosis(report, newAiState);
      setDiagnosis(result);
    } catch (err: unknown) {
      console.error(err);
      setError("Failed to fetch updated diagnosis.");
    } finally {
      setIsLoading(false);
    }
  };

  const handleReset = () => {
    setReport(null);
    setFileName("");
    setDiagnosis(null);
    setError(null);
  };

  return (
    <div className="min-h-screen flex flex-col bg-[#FAFAF9] text-[#1A1A1A]">
      <Header />

      <main className="flex-1 max-w-3xl w-full mx-auto px-4 py-8 animate-fade-in">
        {!report ? (
          /* Initial Upload Section */
          <div className="py-4">
            <div className="mb-6">
              <h2 className="text-xl font-bold text-[#1A1A1A] tracking-tight mb-1">
                System Diagnostics &amp; Bottleneck Analysis
              </h2>
              <p className="text-xs text-stone-600 leading-relaxed">
                Upload your machine telemetry report generated by the collector script to view a deterministic diagnostic analysis and recommended fixes.
              </p>
            </div>

            <FileUpload onReportLoaded={handleReportLoaded} isLoading={isLoading} />
          </div>
        ) : (
          /* Diagnostic Findings View */
          <div>
            <div className="flex items-center justify-between border-b border-stone-200 pb-3 mb-6">
              <div>
                <h2 className="text-lg font-semibold text-[#1A1A1A] tracking-tight">
                  Diagnostic Findings Report
                </h2>
                <p className="text-xs text-stone-500">
                  Source file: <span className="font-mono text-stone-700">{fileName}</span>
                </p>
              </div>

              {diagnosis && (
                <div className="text-xs text-stone-600 font-mono">
                  {diagnosis.issue_count} {diagnosis.issue_count === 1 ? "issue" : "issues"} detected
                </div>
              )}
            </div>

            <SystemOverview report={report} />

            {isLoading ? (
              <div className="py-16 text-center text-xs text-stone-500 font-mono">
                Processing diagnostic report &amp; analyzing metrics...
              </div>
            ) : error ? (
              <div className="py-6 px-4 border border-stone-300 bg-stone-100 text-xs text-stone-800 my-4">
                <p className="font-semibold mb-1">Diagnostic Analysis Failed</p>
                <p className="text-stone-600 mb-3">{error}</p>
                <button
                  onClick={handleReset}
                  className="text-[#4A6FA5] hover:underline font-medium cursor-pointer"
                >
                  Select another telemetry report
                </button>
              </div>
            ) : diagnosis ? (
              <DiagnosticsDashboard
                data={diagnosis}
                fileName={fileName}
                isAiRewrite={isAiRewrite}
                onToggleAiRewrite={handleToggleAiRewrite}
                onReset={handleReset}
                isLoading={isLoading}
              />
            ) : null}
          </div>
        )}
      </main>

      <footer className="border-t border-stone-200 py-6 text-center text-[11px] text-stone-400">
        <div className="max-w-3xl mx-auto px-4 flex justify-between items-center">
          <span>PC Slowdown Diagnoser</span>
          <span>Deterministic Rules Engine • Gemini 2.5</span>
        </div>
      </footer>
    </div>
  );
}
